# Generated by Django 4.2.4 on 2023-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojistiuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
